#include"pch.h"
#include "Resouce.h" 

const std::string ResouceDatabase::mFilePath[RESOUCE_MAX_NUM] = {

		{"Models/Play/AssertLineModel.cmo" },
		{"Models/Play/Boomerang.cmo" },
		{"Models/Play/BossEnemy.cmo" },
		{"Models/Play/Bullet.cmo" },
		{"Models/Play/Conifer.cmo" },
		{"Models/Play/ConiferGroup.cmo" },
		{"Models/Play/fullfence.cmo" },
		{"Models/Play/Grenade.cmo" },
		{"Models/Play/Lance.cmo" },
		{"Models/Play/MachineGun.cmo" },
		{"Models/Play/NewHouseSet.cmo" },
		{"Models/Play/notusedblock.cmo" },
		{"Models/Play/OldHouseSet.cmo" },
		{"Models/Play/Pistol.cmo" },
		{"Models/Play/PixelModel.cmo" },
		{"Models/Play/RocketLauncher.cmo" },
		{"Models/Play/Shop.cmo" },
		{"Models/Play/SkyDome_Daytime.cmo" },
		{"Models/Play/SkyDome_NightTime.cmo" },
		{"Models/Play/Stage.cmo" },
		{"Models/Play/WoodBlock.cmo" },
		{"Models/Play/zonbi.cmo" },
		{"Models/Play/AnimationModel/PlayerStand.cmo" },
		{"Models/Play/AnimationModel/Standard_Run.cmo" },
		{"Textures/Play/Aim.png" },
		{"Textures/Play/Back.png" },
		{"Textures/Play/Circle.png" },
		{"Textures/Play/Confirmation.png" },
		{"Textures/Play/ControlSprite.png" },
		{"Textures/Play/Cursor.png" },
		{"Textures/Play/DefeatEnemy.png" },
		{"Textures/Play/Explanatory.png" },
		{"Textures/Play/FazeGauge.png" },
		{"Textures/Play/Lose.png" },
		{"Textures/Play/MoneyGauge.png" },
		{"Textures/Play/MoonIcon.png" },
		{"Textures/Play/NewDamageString.png" },
		{"Textures/Play/NewMoneyString.png" },
		{"Textures/Play/NewNormalString.png" },
		{"Textures/Play/NewScoreString.png" },
		{"Textures/Play/Pause.png" },
		{"Textures/Play/PhaseCursor.png" },
		{"Textures/Play/PlayerState.png" },
		{"Textures/Play/red.png" },
		{"Textures/Play/Result.png" },
		{"Textures/Play/Score.png" },
		{"Textures/Play/SelectPlate.png" },
		{"Textures/Play/shadow.png" },
		{"Textures/Play/Skip.png" },
		{"Textures/Play/WeaponBackGround.png" },
		{"Textures/Play/WeaponBuyString.png" },
		{"Textures/Play/WeaponSprite.png" },
		{"Textures/Play/Effect/Bomb.png" },
		{"Textures/Play/Effect/Destroy.png" },
		{"Textures/Play/Effect/Disappear.png" },
		{"Textures/Play/Effect/EnemyAttack1.png" },
		{"Textures/Play/Effect/Slash.png" },
		{"Textures/Play/Effect/Spawn.png" },
		{"Textures/Play/Effect/Thrust.png" },
		{"Textures/StageSelect/Cloud.png" },
		{"Textures/StageSelect/Confirmation.png" },
		{"Textures/StageSelect/Cursor.png" },
		{"Textures/StageSelect/SignBoard.png" },
		{"Textures/StageSelect/Stage1.png" },
		{"Textures/StageSelect/Stage10.jpg" },
		{"Textures/StageSelect/Stage2.png" },
		{"Textures/StageSelect/Stage3.png" },
		{"Textures/StageSelect/Stage5.png" },
		{"Textures/StageSelect/Stage6.png" },
		{"Textures/StageSelect/Stage7.png" },
		{"Textures/StageSelect/Stage8.png" },
		{"Textures/StageSelect/Stage9.png" },
		{"Textures/StageSelect/StageNumberFont.png" },
		{"Textures/StageSelect/StageScale.png" },
		{"Textures/StageSelect/StageSelect.png" },
		{"Textures/StageSelect/StageSelectName.png" },
		{"Textures/StageSelect/Star.png" },
		{"Textures/StageSelect/StringEnglish.png" },
		{"Textures/StageSelect/StringJapanise.png" },
		{"Textures/Title/Cloud.png" },
		{"Textures/Title/TitleBar.png" },
		{"Textures/Title/TitleName.png" },
		{"Textures/Title/TITLE_BackGround.png" },

};

/*===================================Don't Touch!=======================================*/

const ResouceRange ResouceDatabase::mEnumClassRange[static_cast<int>(ReadRange::NUM)] = {

	{0,23},
	{24,58},
	{59,78},
	{79,82},

};


