#pragma once

#include<string>

struct ResouceRange
{
	//最小
	int mMin;
	//最大
	int mMax;

};

enum class ReadRange
{
	PLAY_MODELS_RESOUCE,
	PLAY_TEXTURES_RESOUCE,
	STAGESELECT_TEXTURES_RESOUCE,
	TITLE_TEXTURES_RESOUCE,
	NUM,

};

struct ResouceDatabase
{
	//リソース最大数
	static const int RESOUCE_MAX_NUM = 83;
	//ファイルのパスを管理するデータベース変数
	static const std::string mFilePath[RESOUCE_MAX_NUM];
	//列挙型の幅を管理する変数
	static const ResouceRange mEnumClassRange[static_cast<int>(ReadRange::NUM)];
};

enum class PlayModelsResouce
{
	MODEL__ASSERTLINEMODEL = 0,
	MODEL__BOOMERANG,
	MODEL__BOSSENEMY,
	MODEL__BULLET,
	MODEL__CONIFER,
	MODEL__CONIFERGROUP,
	MODEL__FULLFENCE,
	MODEL__GRENADE,
	MODEL__LANCE,
	MODEL__MACHINEGUN,
	MODEL__NEWHOUSESET,
	MODEL__NOTUSEDBLOCK,
	MODEL__OLDHOUSESET,
	MODEL__PISTOL,
	MODEL__PIXELMODEL,
	MODEL__ROCKETLAUNCHER,
	MODEL__SHOP,
	MODEL__SKYDOME_DAYTIME,
	MODEL__SKYDOME_NIGHTTIME,
	MODEL__STAGE,
	MODEL__WOODBLOCK,
	MODEL__ZONBI,
	MODEL__ANIMATIONMODEL_PLAYERSTAND,
	MODEL__ANIMATIONMODEL_STANDARD_RUN,

};

enum class PlayTexturesResouce
{
	TEXTURE__AIM = 24,
	TEXTURE__BACK,
	TEXTURE__CIRCLE,
	TEXTURE__CONFIRMATION,
	TEXTURE__CONTROLSPRITE,
	TEXTURE__CURSOR,
	TEXTURE__DEFEATENEMY,
	TEXTURE__EXPLANATORY,
	TEXTURE__FAZEGAUGE,
	TEXTURE__LOSE,
	TEXTURE__MONEYGAUGE,
	TEXTURE__MOONICON,
	TEXTURE__NEWDAMAGESTRING,
	TEXTURE__NEWMONEYSTRING,
	TEXTURE__NEWNORMALSTRING,
	TEXTURE__NEWSCORESTRING,
	TEXTURE__PAUSE,
	TEXTURE__PHASECURSOR,
	TEXTURE__PLAYERSTATE,
	TEXTURE__RED,
	TEXTURE__RESULT,
	TEXTURE__SCORE,
	TEXTURE__SELECTPLATE,
	TEXTURE__SHADOW,
	TEXTURE__SKIP,
	TEXTURE__WEAPONBACKGROUND,
	TEXTURE__WEAPONBUYSTRING,
	TEXTURE__WEAPONSPRITE,
	TEXTURE__EFFECT_BOMB,
	TEXTURE__EFFECT_DESTROY,
	TEXTURE__EFFECT_DISAPPEAR,
	TEXTURE__EFFECT_ENEMYATTACK1,
	TEXTURE__EFFECT_SLASH,
	TEXTURE__EFFECT_SPAWN,
	TEXTURE__EFFECT_THRUST,

};

enum class StageSelectTexturesResouce
{
	TEXTURE__CLOUD = 59,
	TEXTURE__CONFIRMATION,
	TEXTURE__CURSOR,
	TEXTURE__SIGNBOARD,
	TEXTURE__STAGE1,
	TEXTURE__STAGE10,
	TEXTURE__STAGE2,
	TEXTURE__STAGE3,
	TEXTURE__STAGE5,
	TEXTURE__STAGE6,
	TEXTURE__STAGE7,
	TEXTURE__STAGE8,
	TEXTURE__STAGE9,
	TEXTURE__STAGENUMBERFONT,
	TEXTURE__STAGESCALE,
	TEXTURE__STAGESELECT,
	TEXTURE__STAGESELECTNAME,
	TEXTURE__STAR,
	TEXTURE__STRINGENGLISH,
	TEXTURE__STRINGJAPANISE,

};

enum class TitleTexturesResouce
{
	TEXTURE__CLOUD = 79,
	TEXTURE__TITLEBAR,
	TEXTURE__TITLENAME,
	TEXTURE__TITLE_BACKGROUND,

};


